services:
  db:
    image: postgres:17.2
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - internal_network  # Ajout du réseau interne

  pgadmin:
    image: dpage/pgadmin4 #:8.14.0
    container_name: pgadmin
    restart: always
    ports:
      - "8080:80"  # pgAdmin accessible en externe
    environment:
      PGADMIN_DEFAULT_EMAIL: example@local.org
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - internal_network  # Ajout du réseau interne

  # vscode-web:
  #   image: codercom/code-server:latest
  #   container_name: vscode
  #   environment:
  #     PASSWORD: password # Mot de passe pour sécuriser l'accès à VS Code Web
  #   ports:
  #     - "8888"
  #   volumes:
  #     - vscode:/home/coder
  #   networks:
  #     - internal_network

networks:
  internal_network:
    driver: bridge  # Création d'un réseau interne

volumes:
  postgres-data:
  pgadmin-data:
  # vscode:
